//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventorySystem.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventorySystem.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        

        

        

        

        

        

        

        

        

        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_dashboard {
            get {
                object obj = ResourceManager.GetObject("icon_dashboard", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }

        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_inventory {
            get {
                object obj = ResourceManager.GetObject("icon_inventory", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_history {
            get {
                object obj = ResourceManager.GetObject("icon_history", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_logout {
            get {
                object obj = ResourceManager.GetObject("icon_logout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
            /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Msg_ItemAdded {
            get {
                return ResourceManager.GetString("Msg_ItemAdded", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Error_OutOfStock {
            get {
                return ResourceManager.GetString("Error_OutOfStock", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string CartEmpty {
            get {
                return ResourceManager.GetString("CartEmpty", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string DraftEmpty {
            get {
                return ResourceManager.GetString("DraftEmpty", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string ConfirmSale {
            get {
                return ResourceManager.GetString("ConfirmSale", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string PaymentPrompt {
            get {
                return ResourceManager.GetString("PaymentPrompt", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_Title {
            get {
                return ResourceManager.GetString("POS_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_Customer {
            get {
                return ResourceManager.GetString("POS_Customer", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_OrderDate {
            get {
                return ResourceManager.GetString("POS_OrderDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_DeliveryDate {
            get {
                return ResourceManager.GetString("POS_DeliveryDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_ShippingTo {
            get {
                return ResourceManager.GetString("POS_ShippingTo", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_LineItems {
            get {
                return ResourceManager.GetString("POS_LineItems", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_AddItem {
            get {
                return ResourceManager.GetString("POS_AddItem", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_OrderSummary {
            get {
                return ResourceManager.GetString("POS_OrderSummary", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_Subtotal {
            get {
                return ResourceManager.GetString("POS_Subtotal", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_Tax {
            get {
                return ResourceManager.GetString("POS_Tax", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_Shipping {
            get {
                return ResourceManager.GetString("POS_Shipping", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_GrandTotal {
            get {
                return ResourceManager.GetString("POS_GrandTotal", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_SaveDraft {
            get {
                return ResourceManager.GetString("POS_SaveDraft", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_Checkout {
            get {
                return ResourceManager.GetString("POS_Checkout", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_GridProduct {
            get {
                return ResourceManager.GetString("POS_GridProduct", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_GridQty {
            get {
                return ResourceManager.GetString("POS_GridQty", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_GridStock {
            get {
                return ResourceManager.GetString("POS_GridStock", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_GridPrice {
            get {
                return ResourceManager.GetString("POS_GridPrice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string POS_GridTotal {
            get {
                return ResourceManager.GetString("POS_GridTotal", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_Title {
            get {
                return ResourceManager.GetString("Dash_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_TotalInventory {
            get {
                return ResourceManager.GetString("Dash_TotalInventory", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_TotalRevenue {
            get {
                return ResourceManager.GetString("Dash_TotalRevenue", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_TotalOrders {
            get {
                return ResourceManager.GetString("Dash_TotalOrders", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_LowStock {
            get {
                return ResourceManager.GetString("Dash_LowStock", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_WeeklyRevenue {
            get {
                return ResourceManager.GetString("Dash_WeeklyRevenue", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_MonthlyTrends {
            get {
                return ResourceManager.GetString("Dash_MonthlyTrends", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_SalesTrends {
            get {
                return ResourceManager.GetString("Dash_SalesTrends", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_TopSelling {
            get {
                return ResourceManager.GetString("Dash_TopSelling", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_ItemsSuffix {
            get {
                return ResourceManager.GetString("Dash_ItemsSuffix", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_ValuedAt {
            get {
                return ResourceManager.GetString("Dash_ValuedAt", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_TodayRevenue {
            get {
                return ResourceManager.GetString("Dash_TodayRevenue", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_NewOrders {
            get {
                return ResourceManager.GetString("Dash_NewOrders", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Dash_NeedsReordering {
            get {
                return ResourceManager.GetString("Dash_NeedsReordering", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_MainTitle {
            get {
                return ResourceManager.GetString("Nav_MainTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_Dashboard {
            get {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_Inventory {
            get {
                return ResourceManager.GetString("Nav_Inventory", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_Customers {
            get {
                return ResourceManager.GetString("Nav_Customers", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_Suppliers {
            get {
                return ResourceManager.GetString("Nav_Suppliers", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_POS {
            get {
                return ResourceManager.GetString("Nav_POS", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_Reports {
            get {
                return ResourceManager.GetString("Nav_Reports", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_History {
            get {
                return ResourceManager.GetString("Nav_History", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_UserProfile {
            get {
                return ResourceManager.GetString("Nav_UserProfile", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_Logout {
            get {
                return ResourceManager.GetString("Nav_Logout", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_AddUser {
            get {
                return ResourceManager.GetString("Nav_AddUser", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Nav_LicenseInfo {
            get {
                return ResourceManager.GetString("Nav_LicenseInfo", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_Title {
            get {
                return ResourceManager.GetString("Parts_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_Search {
            get {
                return ResourceManager.GetString("Parts_Search", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_Filter {
            get {
                return ResourceManager.GetString("Parts_Filter", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_AddCategory {
            get {
                return ResourceManager.GetString("Parts_AddCategory", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_AddProduct {
            get {
                return ResourceManager.GetString("Parts_AddProduct", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_Import {
            get {
                return ResourceManager.GetString("Parts_Import", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_Export {
            get {
                return ResourceManager.GetString("Parts_Export", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_Delete {
            get {
                return ResourceManager.GetString("Parts_Delete", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridImage {
            get {
                return ResourceManager.GetString("Parts_GridImage", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridSKU {
            get {
                return ResourceManager.GetString("Parts_GridSKU", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridBarcode {
            get {
                return ResourceManager.GetString("Parts_GridBarcode", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridProduct {
            get {
                return ResourceManager.GetString("Parts_GridProduct", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridCategory {
            get {
                return ResourceManager.GetString("Parts_GridCategory", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridLocation {
            get {
                return ResourceManager.GetString("Parts_GridLocation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridShelf {
            get {
                return ResourceManager.GetString("Parts_GridShelf", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridStock {
            get {
                return ResourceManager.GetString("Parts_GridStock", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridMinStock {
            get {
                return ResourceManager.GetString("Parts_GridMinStock", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridPrice {
            get {
                return ResourceManager.GetString("Parts_GridPrice", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridStatus {
            get {
                return ResourceManager.GetString("Parts_GridStatus", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Parts_GridActions {
            get {
                return ResourceManager.GetString("Parts_GridActions", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_Title {
            get {
                return ResourceManager.GetString("Cust_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_Search {
            get {
                return ResourceManager.GetString("Cust_Search", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_Import {
            get {
                return ResourceManager.GetString("Cust_Import", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_Export {
            get {
                return ResourceManager.GetString("Cust_Export", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_RecordSale {
            get {
                return ResourceManager.GetString("Cust_RecordSale", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_ReceivePayment {
            get {
                return ResourceManager.GetString("Cust_ReceivePayment", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_AddCustomer {
            get {
                return ResourceManager.GetString("Cust_AddCustomer", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_Delete {
            get {
                return ResourceManager.GetString("Cust_Delete", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_GridName {
            get {
                return ResourceManager.GetString("Cust_GridName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_GridPhone {
            get {
                return ResourceManager.GetString("Cust_GridPhone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_GridEmail {
            get {
                return ResourceManager.GetString("Cust_GridEmail", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_GridAddress {
            get {
                return ResourceManager.GetString("Cust_GridAddress", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_GridBalance {
            get {
                return ResourceManager.GetString("Cust_GridBalance", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Cust_GridActions {
            get {
                return ResourceManager.GetString("Cust_GridActions", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_Title {
            get {
                return ResourceManager.GetString("Sup_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_Search {
            get {
                return ResourceManager.GetString("Sup_Search", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_Import {
            get {
                return ResourceManager.GetString("Sup_Import", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_Export {
            get {
                return ResourceManager.GetString("Sup_Export", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_AddBill {
            get {
                return ResourceManager.GetString("Sup_AddBill", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_PaySupplier {
            get {
                return ResourceManager.GetString("Sup_PaySupplier", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_AddSupplier {
            get {
                return ResourceManager.GetString("Sup_AddSupplier", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_Delete {
            get {
                return ResourceManager.GetString("Sup_Delete", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_GridCompany {
            get {
                return ResourceManager.GetString("Sup_GridCompany", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_GridContact {
            get {
                return ResourceManager.GetString("Sup_GridContact", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_GridPhone {
            get {
                return ResourceManager.GetString("Sup_GridPhone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_GridEmail {
            get {
                return ResourceManager.GetString("Sup_GridEmail", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_GridActiveOrders {
            get {
                return ResourceManager.GetString("Sup_GridActiveOrders", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Sup_GridActions {
            get {
                return ResourceManager.GetString("Sup_GridActions", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_Title {
            get {
                return ResourceManager.GetString("Hist_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_Refresh {
            get {
                return ResourceManager.GetString("Hist_Refresh", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_StatActivity {
            get {
                return ResourceManager.GetString("Hist_StatActivity", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_StatOrders {
            get {
                return ResourceManager.GetString("Hist_StatOrders", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_StatPayments {
            get {
                return ResourceManager.GetString("Hist_StatPayments", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_TabInventory {
            get {
                return ResourceManager.GetString("Hist_TabInventory", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_TabCustomers {
            get {
                return ResourceManager.GetString("Hist_TabCustomers", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_TabSuppliers {
            get {
                return ResourceManager.GetString("Hist_TabSuppliers", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_TabOrders {
            get {
                return ResourceManager.GetString("Hist_TabOrders", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColDate {
            get {
                return ResourceManager.GetString("Hist_ColDate", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColAction {
            get {
                return ResourceManager.GetString("Hist_ColAction", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColItem {
            get {
                return ResourceManager.GetString("Hist_ColItem", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColDetails {
            get {
                return ResourceManager.GetString("Hist_ColDetails", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColUser {
            get {
                return ResourceManager.GetString("Hist_ColUser", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColType {
            get {
                return ResourceManager.GetString("Hist_ColType", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColCustomer {
            get {
                return ResourceManager.GetString("Hist_ColCustomer", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColAmount {
            get {
                return ResourceManager.GetString("Hist_ColAmount", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColOrderID {
            get {
                return ResourceManager.GetString("Hist_ColOrderID", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColTotal {
            get {
                return ResourceManager.GetString("Hist_ColTotal", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColStatus {
            get {
                return ResourceManager.GetString("Hist_ColStatus", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColItems {
            get {
                return ResourceManager.GetString("Hist_ColItems", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Hist_ColSupplier {
            get {
                return ResourceManager.GetString("Hist_ColSupplier", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_Title {
            get {
                return ResourceManager.GetString("Rep_Title", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_ValuationTitle {
            get {
                return ResourceManager.GetString("Rep_ValuationTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_CategoryTitle {
            get {
                return ResourceManager.GetString("Rep_CategoryTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_TopProductsTitle {
            get {
                return ResourceManager.GetString("Rep_TopProductsTitle", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_TotalSales {
            get {
                return ResourceManager.GetString("Rep_TotalSales", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_AvgOrder {
            get {
                return ResourceManager.GetString("Rep_AvgOrder", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_ChartValuation {
            get {
                return ResourceManager.GetString("Rep_ChartValuation", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Rep_ChartSales {
            get {
                return ResourceManager.GetString("Rep_ChartSales", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Popup_Phone {
            get {
                return ResourceManager.GetString("Popup_Phone", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Popup_Address {
            get {
                return ResourceManager.GetString("Popup_Address", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Popup_Company {
            get {
                return ResourceManager.GetString("Popup_Company", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Popup_Individual {
            get {
                return ResourceManager.GetString("Popup_Individual", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Popup_Cancel {
            get {
                return ResourceManager.GetString("Popup_Cancel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_TitleNew {
            get {
                return ResourceManager.GetString("AddCust_TitleNew", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_TitleEdit {
            get {
                return ResourceManager.GetString("AddCust_TitleEdit", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_UpdateBtn {
            get {
                return ResourceManager.GetString("AddCust_UpdateBtn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_Section {
            get {
                return ResourceManager.GetString("AddCust_Section", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_FullName {
            get {
                return ResourceManager.GetString("AddCust_FullName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_Email {
            get {
                return ResourceManager.GetString("AddCust_Email", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_Type {
            get {
                return ResourceManager.GetString("AddCust_Type", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_Save {
            get {
                return ResourceManager.GetString("AddCust_Save", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddCust_ReqName {
            get {
                return ResourceManager.GetString("AddCust_ReqName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_TitleNew {
            get {
                return ResourceManager.GetString("AddSup_TitleNew", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_TitleEdit {
            get {
                return ResourceManager.GetString("AddSup_TitleEdit", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_UpdateBtn {
            get {
                return ResourceManager.GetString("AddSup_UpdateBtn", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_Section {
            get {
                return ResourceManager.GetString("AddSup_Section", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_CompanyName {
            get {
                return ResourceManager.GetString("AddSup_CompanyName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_Email {
            get {
                return ResourceManager.GetString("AddSup_Email", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_Type {
            get {
                return ResourceManager.GetString("AddSup_Type", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_Save {
            get {
                return ResourceManager.GetString("AddSup_Save", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string AddSup_ReqName {
            get {
                return ResourceManager.GetString("AddSup_ReqName", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Tran_AmountLabel {
            get {
                return ResourceManager.GetString("Tran_AmountLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Tran_NotesLabel {
            get {
                return ResourceManager.GetString("Tran_NotesLabel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Tran_Confirm {
            get {
                return ResourceManager.GetString("Tran_Confirm", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Tran_Cancel {
            get {
                return ResourceManager.GetString("Tran_Cancel", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Tran_ErrorInvalid {
            get {
                return ResourceManager.GetString("Tran_ErrorInvalid", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Prompt_PaySupplier {
            get {
                return ResourceManager.GetString("Prompt_PaySupplier", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Prompt_AddBill {
            get {
                return ResourceManager.GetString("Prompt_AddBill", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Prompt_RecordSale {
            get {
                return ResourceManager.GetString("Prompt_RecordSale", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string.
        /// </summary>
        internal static string Prompt_ReceivePayment {
            get {
                return ResourceManager.GetString("Prompt_ReceivePayment", resourceCulture);
            }
        }
    }
}

